### ISSUE TITLE
How to save edited document to local storage in flutter?

### ISSUE THREAD

**Issue by abdulhaseeb725** [PDFTron/pdftron-flutter#235]
I have used saveDocument() method but it's not saving. How do I saved the document after editing in to my local storage in flutter when click on leading navigation button.

**Comment by terryyoon-pdftron** [comment]
Hi there. On my end I can verify that the saveDocument function works properly. Can you confirm that the function is being called to begin with and that you're checking the correct path? If that's the case, could you provide more details as to how you're calling the saveDocument function and why you think it's not working?

**Comment by abdulhaseeb725** [comment]
It's working but the path it gives file is not there. Also I want to save the file in Downloads folder but I don't know how to give saving path to saveDocument method. Can you provide a sample code for that. I already searched through documentation but I did not find anything regarding this in FLUTTER.

**Comment by terryyoon-pdftron** [comment]
The saveDocument function itself does not provide a way to specify a saving path, but you can use the [copy](https://api.flutter.dev/flutter/dart-io/File/copy.html) function in the `dart:io` library to copy the file to your desired location. 

You can also utilize the [`permission_handler`](https://pub.dev/packages/permission_handler) library to make sure your app has the permission to access the local storage, and the [`path_provider`](https://pub.dev/packages/path_provider) library to find the path of commonly used locations in the filesystem.

Here's an example that will work for both Android and iOS:

```dart
var status = await Permission.storage.request(); // permission_handler
if (status.isGranted) {
  Directory? directory;

  if (Platform.isIOS) {
    // create a folder with the name of the app
    directory = await getApplicationDocumentsDirectory(); // path_provider
  } else {
    // global download folder
    directory = Directory('/storage/emulated/0/Download');
  }

  var path = await controller.saveDocument();
  var file = File(path!);
  if (await file.exists()) {
    await file.copy(directory.path + '/test.pdf');
    // delete the original file if desired
    file.delete();
  }
}
```
If you're using Android, make sure the following line is in your `AndroidManifest.xml` file:
```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

If you're using iOS, please edit your `Info.plist` file to include the following lines so that the app's folder is visible from the File app:
```
<key>LSSupportsOpeningDocumentsInPlace</key>
<true/>
<key>UIFileSharingEnabled</key>
<true/>
```

**Comment by abdulhaseeb725** [comment]
Yes It's saving document but it is saving it in original form means I added test on pdf and then save it but when I open the file the added text was not there and the file is in original form. Can you please tell me how can I save the edited form of pdf?

**Comment by abdulhaseeb725** [comment]
Thanks it's working great. I have another query can I edit image and save it? Because it is giving error when I try to do it. So is this functionality is there?
